### ISSUE TITLE
Commit history from D7

### ISSUE THREAD

**Issue by docwilmot** [altagrade/search_index#2]
If this was ported from a D7 module, we should maintain the commit logs.

**Comment by alanmels** [comment]
@docwilmot, I understand we should maintain the commit logs to respect the previous contributor's efforts, however in this case the [project](https://www.drupal.org/project/search_index) was created by our team and we don't mind if credits start from a fresh, also taking into account that the module's machine name changed for better fit and that if https://github.com/backdrop/backdrop-issues/issues/4197 is accepted into core, then this project will probably seize to exist.

**Comment by docwilmot** [comment]
Fair enough
