### ISSUE TITLE
No config management

### ISSUE THREAD

**Issue by docwilmot** [altagrade/search_index#3]
This module uses and introduces new config but doesn't have a default config file, nor the appropriate hook.

**Comment by alanmels** [comment]
@docwilmot, thanks for the report. However, I'd concentrate on https://github.com/backdrop/backdrop-issues/issues/4197 and if it gets into core, then I'd like to stop spending time on this module.

**Comment by jenlampton** [comment]
This got into core.  Closing?  
(see also https://github.com/backdrop-contrib/search_index_options/issues/4)
