### ISSUE TITLE
Update the README to indicate that this module is no longer necessary

### ISSUE THREAD

**Issue by jenlampton** [altagrade/search_index#4]
Since https://github.com/backdrop/backdrop-issues/issues/4197 got into core, we don't need this contrib module anymore, right? 

If so, we should update the README to indicate that this feature is now part of core, and that the module should be disabled and uninstalled if people are running 1.16.0 or later.

**Comment by jenlampton** [comment]
PR filed: https://github.com/backdrop-contrib/search_index_options/pull/5

**Comment by yorkshire-pudding** [comment]
@jenlampton - This module duplicates some of what is in core (which can lead to confusion - I don't know about performance but I can imagine it could), but does have additional functionality:

- statistics per content type
- The ability to exclude certain nodes from the index (though I found this needed [Search Index Wipe](https://github.com/backdrop-contrib/searchindex_wipe) to be effective and ended up porting [Search Exclude NID](https://github.com/backdrop-contrib/search_exclude_nid) which removes from the search results and therefore gives an instant result)

I think the statistics could be a welcome and appropriate addition to core, but don't know about excluding nodes from the index; it is definitely worthy of contrib, but may not be a core feature.
